const ethnicityOptions = [
  'Prefer not to say',
  'White - British',
  'White - Irish',
  'White - Other',
  'Mixed - White and Black Caribbean',
  'Mixed - White and Black African',
  'Mixed - White and Asian',
  'Mixed - Other',
  'Asian or Asian British - Indian',
  'Asian or Asian British - Pakistani',
  'Asian or Asian British - Bangladeshi',
  'Asian or Asian British - Chinese',
  'Asian or Asian British - Other',
  'Black or Black British - African',
  'Black or Black British - Caribbean',
  'Black or Black British - Other',
  'Arab',
  'Gypsy or Irish Traveller',
  'Roma',
  'Other Ethnic Group',
  'Hispanic or Latino',
  'Native American or Alaska Native',
  'Native Hawaiian or Other Pacific Islander',
  'Jewish',
  'South East Asian',
  'East Asian',
  'Central Asian',
  'North African',
  'Sub-Saharan African',
  'Other (please specify)',
];

export default ethnicityOptions; 