// Flattened list of all hobbies (matching industries display style)
const hobbies = [
  'Art',
  'Baking',
  'Blogging',
  'Board Games',
  'Charity',
  'Chess',
  'Choir',
  'Cooking',
  'Crafts',
  'Creative Writing',
  'Dance',
  'Fashion',
  'Film & TV',
  'Guitar',
  'Hiking',
  'Journalism',
  'Language Learning',
  'Martial Arts',
  'Meditation',
  'Musical Theater',
  'Nature',
  'Piano',
  'Podcasts',
  'Programming',
  'Researching',
  'Rock Climbing',
  'Robotics',
  'Singing',
  'Skateboarding',
  'Swimming',
  'Table Tennis',
  'Teaching',
  'Travel',
  'Video Games',
  'Violin',
  'Vlogging',
  // Sports
  'Badminton',
  'Baseball',
  'Basketball',
  'Biking',
  'Boxing',
  'Cricket',
  'Cycling',
  'Football',
  'Golf',
  'Running',
  'Rugby',
  'Tennis',
  'Volleyball',
];

export default hobbies;
