const hobbies = [
  'Football',
  'Cricket',
  'Rugby',
  'Tennis',
  'Cycling',
  'Running',
  'Swimming',
  'Hiking',
  'Dancing',
  'Singing',
  'Playing an Instrument',
  'Reading',
  'Writing', 
  'Drawing',
  'Painting',
  'Photography',
  'Cooking',
  'Baking',
  'Gardening',
  'Travel',
  'Volunteering',
  'Chess',
  'Board Games',
  'Video Games',
  'Fishing',
  'Camping',
  'Yoga',
  'Meditation',
  'Martial Arts',
  'Collecting',
  'Bird Watching',
  'Blogging',
  'Podcasting',
  'Film & TV',
  'Fashion',
  'Basketball',
  'Baseball',
  'Volleyball',
  'Table Tennis',
  'Badminton',
  'Golf',
  'Rock Climbing',
  'Skateboarding',
  'Surfing',
  'Skiing',
  'Snowboarding',
  'Ice Skating',
  'Roller Skating',
  'Ballet',
  'Jazz Dance',
  'Hip Hop Dance',
  'Ballroom Dancing',
  'Opera Singing',
  'Choir',
  'Guitar',
  'Piano',
  'Violin',
  'Drums',
  'Saxophone',
  'Poetry',
  'Creative Writing',
  'Journalism',
  'Calligraphy',
  'Sculpture',
  'Pottery',
  'Digital Art',
  'Animation',
  'Street Photography',
  'Wildlife Photography',
  'Portrait Photography',
  'International Cuisine',
  'BBQ & Grilling',
  'Wine Tasting',
  'Beer Brewing',
  'Cake Decorating',
  'Bread Making',
  'Urban Gardening',
  'Flower Arranging',
  'Backpacking',
  'Road Trips',
  'Language Learning',
  'Teaching',
  'Animal Rescue',
  'Environmental Conservation',
  'Checkers',
  'Bridge',
  'Mahjong',
  'Dungeons & Dragons',
  'PC Gaming',
  'Console Gaming',
  'Mobile Gaming',
  'Deep Sea Fishing',
  'Fly Fishing',
  'Ice Fishing',
  'Wilderness Camping',
  'RV Camping',
  'Beach Camping',
  'Pilates',
  'Tai Chi',
  'Mindfulness',
  'Karate',
  'Judo',
  'Taekwondo',
  'Stamp Collecting',
  'Coin Collecting',
  'Comic Book Collecting',
  'Record Collecting',
  'Nature Photography',
  'Vlogging',
  'Web Design',
  'DIY Crafts',
  'Woodworking',
  'Metalworking',
  'Jewelry Making',
  'Knitting',
  'Crocheting',
  'Sewing',
  'Quilting',
  'Interior Design',
  'Model Building',
  'Remote Control Cars',
  'Drone Flying',
  'Astronomy',
  'Genealogy',
  'Magic Tricks',
  'Juggling',
  'Stand-up Comedy',
  'Acting',
  'Musical Theater',
  'Other'
];

export default hobbies; 