const industries = [
  'Agriculture', 
  'Arts & Culture', 
  'Automotive', 
  'Construction', 
  'Consulting', 
  'Cybersecurity',
  'Education', 
  'Engineering', 
  'Energy', 
  'Entertainment', 
  'Environmental Services',
  'Finance', 
  'Government', 
  'Healthcare', 
  'Hospitality', 
  'Insurance',
  'Legal', 
  'Logistics', 
  'Manufacturing', 
  'Marketing', 
  'Media',
  'Non-Profit', 
  'Pharmaceuticals', 
  'Real Estate', 
  'Retail', 
  'Science & Research', 
  'Nature/Conservation',
  'Humanitarian',
  'Sports & Recreation', 
  'Technology', 
  'Telecommunications', 
  'Tourism', 
  'Transportation'
];

export default industries; 