const industries = [
  'Technology',
  'Finance',
  'Healthcare',
  'Education',
  'Engineering',
  'Consulting',
  'Legal',
  'Marketing',
  'Media & Entertainment',
  'Retail',
  'Hospitality',
  'Real Estate',
  'Construction',
  'Transportation',
  'Manufacturing',
  'Energy',
  'Government',
  'Nonprofit',
  'Science & Research',
  'Arts & Design',
  'Sports & Recreation',
  'Agriculture',
  'Telecommunications',
  'Automotive',
  'Aerospace',
  'Pharmaceuticals',
  'Other',
];

export default industries; 