const subjects = [
  'Mathematics',
  'English Language',
  'English Literature',
  'Biology',
  'Chemistry',
  'Physics',
  'Science (Combined)',
  'History',
  'Geography',
  'French',
  'Spanish',
  'German',
  'Art & Design',
  'Music',
  'Drama',
  'Physical Education',
  'Religious Studies',
  'Computer Science',
  'Design & Technology',
  'Business Studies',
  'Economics',
  'Psychology',
  'Sociology',
  'Media Studies',
  'Politics',
  'Philosophy',
  'Further Mathematics',
  'Statistics',
  'Latin',
  'Classical Civilisation',
  'Other'
];

export default subjects; 