name: Linting and Code Qode Quality Check

on:
  push:
    branches: '**'
    tags: '**'
  pull_request:
    branches: '**'

jobs:
  lint:
    name: Setup Node.js
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
      if: always()

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      if: always()