name: Linting and Code Quality Check

on:
  push:
    branches: '**'
    tags: '**'

jobs:
  lint:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write  # Required for SARIF upload

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
      if: always()

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      if: always()